language: python
python:
  - "2.7"

before_install:
  - pip install https://github.com/koenbok/Cactus/archive/master.zip
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - cactus build
  - cd .build 
  - CHECK=$(for file in *.html; do python ../html5check.py -geh $file; done;)
  - if [[ ! -z $(echo "$CHECK" | grep -vE 'iframe') ]]; then echo "$CHECK"; exit 1; fi;
